---
sudo: false
language: ruby
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
matrix:
  include:
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.9.1" STRICT_VARIABLES="yes"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.10.0" STRICT_VARIABLES="yes"
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5.0.0" STRICT_VARIABLES="yes"
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5.1.0" STRICT_VARIABLES="yes"
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5.2.0" STRICT_VARIABLES="yes"
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5" STRICT_VARIABLES="yes"
